server:
  port: 80
cloud:
  aws:
    credentials:
      access-key: XXX
      secret-key: XXX
    region:
      static: XXX
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
